# Generated by Django 4.1.4 on 2023-01-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findin', '0002_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='code',
        ),
    ]
